version: '3'
volumes:
  grafana:
services:
  db:
    image: postgres:9.6.15-alpine
    container_name: xolon_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  cache:
    image: redis:latest
    container_name: xolon_cache
    ports:
      - 6379:6379
